[package]
name = "example_host"
version = "0.1.0"
authors = ["Alec Deason <wasm_plugins@tinycountry.com>"]
edition = "2018"

[dependencies]
host = { path = "../../host" }
bincode = "1.3.2"
getrandom = "0.2.2"
