[package]
name = "example_guest"
version = "0.1.0"
authors = ["Alec Deason <wasm_plugins@tinycountry.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
guest = {path = "../../guest" }
getrandom = { version = "0.2.2", features = ["custom"] }
bincode = "1.3.2"
